#!/bin/bash

opam init --root=$HOME/opam-root -j $NJOBS --compiler=$COMPILER -n -y
eval $(opam config --root=${HOME}/opam-root env)
opam config list
opam install -j $NJOBS -y camlp5 ocamlfind $EXTRA_OPAM
opam list
mkdir -p $HOME/opam-cache
tar czf $HOME/opam-cache/cache-$COMPILER.tgz $HOME/opam-root
