#!/bin/bash

set -e
#set -x

while [ ! -z "$1" ]; do
 if [ -e "$1" ]; then
  case "$1" in
  */opam)
    echo Linting $1
    # 21: incorrect opam version
    opam lint --warn=-21 $1
    echo
  ;;
  *)
    echo Ignoring $1
    echo
  ;;
  esac
 fi
 shift
done
