#!/bin/bash
#
# Script to be run on the machine serving the git checkout via HTTP

MAILTO=enrico.tassi@inria.fr
LOG=/tmp/coq-opam-archive.log

notify() {
(echo "OPAM $1 on repo $2 failed:"; cat $LOG) | mail -s 'OPAM alert' $MAILTO
echo "OPAM $1 on repo $2 failed:"; cat $LOG
}

OPAM=/usr/local/bin/opam2
OPAMCHECKOPTS=--cycles

for repo in $@; do
        cd $repo
        $OPAM admin check $OPAMCHECKOPTS > $LOG 2>&1
        if [ "$?" != "0" ]; then notify check $repo;
        else
                $OPAM admin make > $LOG 2>&1
                if [ "$?" != "0" ]; then notify make $repo; fi
        fi
        cd ..
done
